language: lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - sudo apt-get -y install sbcl realpath

before_script:
  - git submodule update --init
  - /bin/sh ./bootstrap.sh

script:
  - test/e2e.sh
