language: lisp

env:
  matrix:
    - LISP=sbcl
    # - LISP=ccl

install:
  - sudo apt-get -y install sbcl realpath

before_script:
  - /bin/sh ./bootstrap.sh

script:
  - /bin/sh ./bootstrap.sh test
